USE [AlDiaDB];
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE dbo.usp_ConsultarInicializacion
 @HayUsuarios BIT OUTPUT, @HayAdministradorActivo BIT OUTPUT
AS
BEGIN
 SET NOCOUNT ON;
SELECT @HayUsuarios=CASE WHEN EXISTS(SELECT 1 FROM dbo.Usuarios) THEN 1 ELSE 0 END, @HayAdministradorActivo=CASE WHEN EXISTS(SELECT 1 FROM dbo.Usuarios WHERE Rol='Administrador' AND Estado=1) THEN 1 ELSE 0 END;
END;
GO
