namespace AlDia.UI.Formularios;

partial class FrmDashsbor
{
    private System.ComponentModel.IContainer components;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        ayudaControles = new ToolTip(components);
        panelAreaTrabajo = new Panel();
        panelCuerpo = new Panel();
        panelCabecera = new Panel();
        lblTitulo = new Label();
        lblSeccion = new Label();
        iconCabecera = new FontAwesome.Sharp.IconPictureBox();
        lblCabeceraDetalle = new Label();
        lineaCabecera = new Panel();
        panelLateral = new Panel();
        panelMenu = new Panel();
        panelMarca = new Panel();
        panelSesion = new Panel();
        lineaLateral = new Panel();
        fondoMarca = new AlDia.UI.Controles.PanelTarjeta();
        iconMarca = new FontAwesome.Sharp.IconPictureBox();
        lblMarca = new Label();
        lblMarcaDetalle = new Label();
        lineaMarca = new Panel();
        lblMenuPrincipal = new Label();
        btnInicio = new FontAwesome.Sharp.IconButton();
        btnClientes = new FontAwesome.Sharp.IconButton();
        btnEquipos = new FontAwesome.Sharp.IconButton();
        btnOrdenes = new FontAwesome.Sharp.IconButton();
        btnInventario = new FontAwesome.Sharp.IconButton();
        btnPagos = new FontAwesome.Sharp.IconButton();
        btnReportes = new FontAwesome.Sharp.IconButton();
        lblAdministracion = new Label();
        btnCatalogos = new FontAwesome.Sharp.IconButton();
        btnUsuarios = new FontAwesome.Sharp.IconButton();
        lineaSesion = new Panel();
        iconUsuario = new FontAwesome.Sharp.IconPictureBox();
        lblUsuario = new Label();
        lblRol = new Label();
        btnCerrarSesion = new FontAwesome.Sharp.IconButton();
        tablaContenido = new TableLayoutPanel();
        panelIntroduccion = new Panel();
        lblResumen = new Label();
        tarjetaResumen = new AlDia.UI.Controles.PanelTarjeta();
        tablaIndicadores = new TableLayoutPanel();
        tarjetaOrdenes = new Panel();
        lblOrdenesTitulo = new Label();
        lblOrdenesValor = new Label();
        tarjetaReparacion = new Panel();
        lblReparacionTitulo = new Label();
        lblReparacionValor = new Label();
        tarjetaEntrega = new Panel();
        lblEntregaTitulo = new Label();
        lblEntregaValor = new Label();
        tarjetaOrdenesRecientes = new AlDia.UI.Controles.PanelTarjeta();
        tablaOrdenes = new TableLayoutPanel();
        panelTituloOrdenes = new Panel();
        lblOrdenesRecientes = new Label();
        btnVerOrdenes = new FontAwesome.Sharp.IconButton();
        tablaEncabezadoOrdenes = new TableLayoutPanel();
        lblColumnaOrden = new Label();
        lblColumnaCliente = new Label();
        lblColumnaEquipo = new Label();
        lblColumnaEstado = new Label();
        tablaSinOrdenes = new TableLayoutPanel();
        lblSinOrdenes = new Label();
        lblPie = new Label();
        panelAreaTrabajo.SuspendLayout();
        panelCuerpo.SuspendLayout();
        panelCabecera.SuspendLayout();
        lineaCabecera.SuspendLayout();
        panelLateral.SuspendLayout();
        panelMenu.SuspendLayout();
        panelMarca.SuspendLayout();
        panelSesion.SuspendLayout();
        lineaLateral.SuspendLayout();
        fondoMarca.SuspendLayout();
        lineaMarca.SuspendLayout();
        lineaSesion.SuspendLayout();
        tablaContenido.SuspendLayout();
        panelIntroduccion.SuspendLayout();
        tarjetaResumen.SuspendLayout();
        tablaIndicadores.SuspendLayout();
        tarjetaOrdenes.SuspendLayout();
        tarjetaReparacion.SuspendLayout();
        tarjetaEntrega.SuspendLayout();
        tarjetaOrdenesRecientes.SuspendLayout();
        tablaOrdenes.SuspendLayout();
        panelTituloOrdenes.SuspendLayout();
        tablaEncabezadoOrdenes.SuspendLayout();
        tablaSinOrdenes.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)iconCabecera).BeginInit();
        ((System.ComponentModel.ISupportInitialize)iconMarca).BeginInit();
        ((System.ComponentModel.ISupportInitialize)iconUsuario).BeginInit();
        SuspendLayout();
        // panelAreaTrabajo
        panelAreaTrabajo.Name = "panelAreaTrabajo";
        panelAreaTrabajo.Location = new Point(236, 0);
        panelAreaTrabajo.Size = new Size(1124, 850);
        panelAreaTrabajo.BackColor = Color.FromArgb(244, 246, 250);
        panelAreaTrabajo.Dock = DockStyle.Fill;
        // panelCuerpo
        panelCuerpo.Name = "panelCuerpo";
        panelCuerpo.Location = new Point(0, 78);
        panelCuerpo.Size = new Size(1124, 772);
        panelCuerpo.BackColor = Color.FromArgb(244, 246, 250);
        panelCuerpo.Dock = DockStyle.Fill;
        panelCuerpo.Padding = new Padding(28, 24, 28, 16);
        panelCuerpo.AutoScroll = true;
        // panelCabecera
        panelCabecera.Name = "panelCabecera";
        panelCabecera.Location = new Point(0, 0);
        panelCabecera.Size = new Size(1124, 78);
        panelCabecera.BackColor = Color.White;
        panelCabecera.Dock = DockStyle.Top;
        // lblTitulo
        lblTitulo.Name = "lblTitulo";
        lblTitulo.Location = new Point(28, 10);
        lblTitulo.Size = new Size(300, 42);
        lblTitulo.Text = "Inicio";
        lblTitulo.Font = new Font("Segoe UI Semibold", 17F, FontStyle.Bold, GraphicsUnit.Point);
        lblTitulo.ForeColor = Color.FromArgb(20, 43, 78);
        lblTitulo.BackColor = Color.Transparent;
        lblTitulo.AutoEllipsis = true;
        // lblSeccion
        lblSeccion.Name = "lblSeccion";
        lblSeccion.Location = new Point(29, 52);
        lblSeccion.Size = new Size(300, 18);
        lblSeccion.Text = "PANEL GENERAL";
        lblSeccion.Font = new Font("Segoe UI", 8F, FontStyle.Regular, GraphicsUnit.Point);
        lblSeccion.ForeColor = Color.FromArgb(103, 116, 137);
        lblSeccion.BackColor = Color.Transparent;
        lblSeccion.AutoEllipsis = true;
        // iconCabecera
        iconCabecera.Name = "iconCabecera";
        iconCabecera.Location = new Point(876, 27);
        iconCabecera.Size = new Size(24, 24);
        iconCabecera.IconChar = FontAwesome.Sharp.IconChar.Tools;
        iconCabecera.IconFont = FontAwesome.Sharp.IconFont.Auto;
        iconCabecera.IconSize = 24;
        iconCabecera.IconColor = Color.FromArgb(37, 99, 235);
        iconCabecera.ForeColor = Color.FromArgb(37, 99, 235);
        iconCabecera.BackColor = Color.White;
        iconCabecera.TabStop = false;
        iconCabecera.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        // lblCabeceraDetalle
        lblCabeceraDetalle.Name = "lblCabeceraDetalle";
        lblCabeceraDetalle.Location = new Point(909, 28);
        lblCabeceraDetalle.Size = new Size(184, 26);
        lblCabeceraDetalle.Text = "Gestión del taller";
        lblCabeceraDetalle.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        lblCabeceraDetalle.ForeColor = Color.FromArgb(103, 116, 137);
        lblCabeceraDetalle.BackColor = Color.Transparent;
        lblCabeceraDetalle.AutoEllipsis = true;
        lblCabeceraDetalle.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        // lineaCabecera
        lineaCabecera.Name = "lineaCabecera";
        lineaCabecera.Location = new Point(0, 77);
        lineaCabecera.Size = new Size(1124, 1);
        lineaCabecera.BackColor = Color.FromArgb(230, 234, 240);
        lineaCabecera.Dock = DockStyle.Bottom;
        // panelLateral
        panelLateral.Name = "panelLateral";
        panelLateral.Location = new Point(0, 0);
        panelLateral.Size = new Size(236, 850);
        panelLateral.BackColor = Color.White;
        panelLateral.Dock = DockStyle.Left;
        panelLateral.Padding = new Padding(0, 0, 1, 0);
        // panelMenu
        panelMenu.Name = "panelMenu";
        panelMenu.Location = new Point(0, 110);
        panelMenu.Size = new Size(235, 648);
        panelMenu.BackColor = Color.White;
        panelMenu.Dock = DockStyle.Fill;
        panelMenu.AutoScroll = true;
        // panelMarca
        panelMarca.Name = "panelMarca";
        panelMarca.Location = new Point(0, 0);
        panelMarca.Size = new Size(235, 110);
        panelMarca.BackColor = Color.White;
        panelMarca.Dock = DockStyle.Top;
        // panelSesion
        panelSesion.Name = "panelSesion";
        panelSesion.Location = new Point(0, 758);
        panelSesion.Size = new Size(235, 92);
        panelSesion.BackColor = Color.FromArgb(248, 250, 253);
        panelSesion.Dock = DockStyle.Bottom;
        // lineaLateral
        lineaLateral.Name = "lineaLateral";
        lineaLateral.Location = new Point(235, 0);
        lineaLateral.Size = new Size(1, 850);
        lineaLateral.BackColor = Color.FromArgb(230, 234, 240);
        lineaLateral.Dock = DockStyle.Right;
        // fondoMarca
        fondoMarca.Name = "fondoMarca";
        fondoMarca.Location = new Point(20, 27);
        fondoMarca.Size = new Size(48, 48);
        fondoMarca.BackColor = Color.FromArgb(20, 43, 78);
        fondoMarca.ColorBorde = Color.FromArgb(20, 43, 78);
        fondoMarca.RadioBorde = 13;
        // iconMarca
        iconMarca.Name = "iconMarca";
        iconMarca.Location = new Point(10, 10);
        iconMarca.Size = new Size(28, 28);
        iconMarca.IconChar = FontAwesome.Sharp.IconChar.Tools;
        iconMarca.IconFont = FontAwesome.Sharp.IconFont.Auto;
        iconMarca.IconSize = 28;
        iconMarca.IconColor = Color.White;
        iconMarca.ForeColor = Color.White;
        iconMarca.BackColor = Color.FromArgb(20, 43, 78);
        iconMarca.TabStop = false;
        // lblMarca
        lblMarca.Name = "lblMarca";
        lblMarca.Location = new Point(80, 21);
        lblMarca.Size = new Size(136, 40);
        lblMarca.Text = "AL DÍA";
        lblMarca.Font = new Font("Segoe UI Semibold", 17F, FontStyle.Bold, GraphicsUnit.Point);
        lblMarca.ForeColor = Color.FromArgb(20, 43, 78);
        lblMarca.BackColor = Color.Transparent;
        lblMarca.AutoEllipsis = true;
        // lblMarcaDetalle
        lblMarcaDetalle.Name = "lblMarcaDetalle";
        lblMarcaDetalle.Location = new Point(80, 61);
        lblMarcaDetalle.Size = new Size(148, 25);
        lblMarcaDetalle.Text = "Gestión del taller";
        lblMarcaDetalle.Font = new Font("Segoe UI", 8.2F, FontStyle.Regular, GraphicsUnit.Point);
        lblMarcaDetalle.ForeColor = Color.FromArgb(103, 116, 137);
        lblMarcaDetalle.BackColor = Color.Transparent;
        lblMarcaDetalle.AutoEllipsis = true;
        // lineaMarca
        lineaMarca.Name = "lineaMarca";
        lineaMarca.Location = new Point(20, 109);
        lineaMarca.Size = new Size(195, 1);
        lineaMarca.BackColor = Color.FromArgb(230, 234, 240);
        // lblMenuPrincipal
        lblMenuPrincipal.Name = "lblMenuPrincipal";
        lblMenuPrincipal.Location = new Point(24, 18);
        lblMenuPrincipal.Size = new Size(190, 24);
        lblMenuPrincipal.Text = "MENÚ PRINCIPAL";
        lblMenuPrincipal.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold, GraphicsUnit.Point);
        lblMenuPrincipal.ForeColor = Color.FromArgb(103, 116, 137);
        lblMenuPrincipal.BackColor = Color.Transparent;
        lblMenuPrincipal.AutoEllipsis = true;
        // btnInicio
        btnInicio.Name = "btnInicio";
        btnInicio.Location = new Point(12, 52);
        btnInicio.Size = new Size(211, 46);
        btnInicio.Text = "Inicio";
        btnInicio.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnInicio.ForeColor = Color.FromArgb(37, 99, 235);
        btnInicio.BackColor = Color.FromArgb(234, 240, 252);
        btnInicio.IconChar = FontAwesome.Sharp.IconChar.House;
        btnInicio.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnInicio.IconColor = Color.FromArgb(37, 99, 235);
        btnInicio.IconSize = 22;
        btnInicio.FlatStyle = FlatStyle.Flat;
        btnInicio.FlatAppearance.BorderSize = 0;
        btnInicio.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnInicio.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnInicio.TextAlign = ContentAlignment.MiddleLeft;
        btnInicio.ImageAlign = ContentAlignment.MiddleLeft;
        btnInicio.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnInicio.Padding = new Padding(12, 0, 0, 0);
        btnInicio.Cursor = Cursors.Hand;
        btnInicio.UseVisualStyleBackColor = false;
        btnInicio.TabIndex = 0;
        btnInicio.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnClientes
        btnClientes.Name = "btnClientes";
        btnClientes.Location = new Point(12, 102);
        btnClientes.Size = new Size(211, 46);
        btnClientes.Text = "Clientes";
        btnClientes.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnClientes.ForeColor = Color.FromArgb(20, 43, 78);
        btnClientes.BackColor = Color.White;
        btnClientes.IconChar = FontAwesome.Sharp.IconChar.Users;
        btnClientes.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnClientes.IconColor = Color.FromArgb(103, 116, 137);
        btnClientes.IconSize = 22;
        btnClientes.FlatStyle = FlatStyle.Flat;
        btnClientes.FlatAppearance.BorderSize = 0;
        btnClientes.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnClientes.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnClientes.TextAlign = ContentAlignment.MiddleLeft;
        btnClientes.ImageAlign = ContentAlignment.MiddleLeft;
        btnClientes.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnClientes.Padding = new Padding(12, 0, 0, 0);
        btnClientes.Cursor = Cursors.Hand;
        btnClientes.UseVisualStyleBackColor = false;
        btnClientes.TabIndex = 1;
        btnClientes.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnEquipos
        btnEquipos.Name = "btnEquipos";
        btnEquipos.Location = new Point(12, 152);
        btnEquipos.Size = new Size(211, 46);
        btnEquipos.Text = "Equipos";
        btnEquipos.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnEquipos.ForeColor = Color.FromArgb(20, 43, 78);
        btnEquipos.BackColor = Color.White;
        btnEquipos.IconChar = FontAwesome.Sharp.IconChar.Laptop;
        btnEquipos.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnEquipos.IconColor = Color.FromArgb(103, 116, 137);
        btnEquipos.IconSize = 22;
        btnEquipos.FlatStyle = FlatStyle.Flat;
        btnEquipos.FlatAppearance.BorderSize = 0;
        btnEquipos.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnEquipos.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnEquipos.TextAlign = ContentAlignment.MiddleLeft;
        btnEquipos.ImageAlign = ContentAlignment.MiddleLeft;
        btnEquipos.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnEquipos.Padding = new Padding(12, 0, 0, 0);
        btnEquipos.Cursor = Cursors.Hand;
        btnEquipos.UseVisualStyleBackColor = false;
        btnEquipos.TabIndex = 2;
        btnEquipos.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnOrdenes
        btnOrdenes.Name = "btnOrdenes";
        btnOrdenes.Location = new Point(12, 202);
        btnOrdenes.Size = new Size(211, 46);
        btnOrdenes.Text = "Órdenes de servicio";
        btnOrdenes.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnOrdenes.ForeColor = Color.FromArgb(20, 43, 78);
        btnOrdenes.BackColor = Color.White;
        btnOrdenes.IconChar = FontAwesome.Sharp.IconChar.ClipboardList;
        btnOrdenes.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnOrdenes.IconColor = Color.FromArgb(103, 116, 137);
        btnOrdenes.IconSize = 22;
        btnOrdenes.FlatStyle = FlatStyle.Flat;
        btnOrdenes.FlatAppearance.BorderSize = 0;
        btnOrdenes.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnOrdenes.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnOrdenes.TextAlign = ContentAlignment.MiddleLeft;
        btnOrdenes.ImageAlign = ContentAlignment.MiddleLeft;
        btnOrdenes.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnOrdenes.Padding = new Padding(12, 0, 0, 0);
        btnOrdenes.Cursor = Cursors.Hand;
        btnOrdenes.UseVisualStyleBackColor = false;
        btnOrdenes.TabIndex = 3;
        btnOrdenes.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnInventario
        btnInventario.Name = "btnInventario";
        btnInventario.Location = new Point(12, 252);
        btnInventario.Size = new Size(211, 46);
        btnInventario.Text = "Inventario";
        btnInventario.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnInventario.ForeColor = Color.FromArgb(20, 43, 78);
        btnInventario.BackColor = Color.White;
        btnInventario.IconChar = FontAwesome.Sharp.IconChar.BoxesStacked;
        btnInventario.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnInventario.IconColor = Color.FromArgb(103, 116, 137);
        btnInventario.IconSize = 22;
        btnInventario.FlatStyle = FlatStyle.Flat;
        btnInventario.FlatAppearance.BorderSize = 0;
        btnInventario.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnInventario.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnInventario.TextAlign = ContentAlignment.MiddleLeft;
        btnInventario.ImageAlign = ContentAlignment.MiddleLeft;
        btnInventario.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnInventario.Padding = new Padding(12, 0, 0, 0);
        btnInventario.Cursor = Cursors.Hand;
        btnInventario.UseVisualStyleBackColor = false;
        btnInventario.TabIndex = 4;
        btnInventario.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnPagos
        btnPagos.Name = "btnPagos";
        btnPagos.Location = new Point(12, 302);
        btnPagos.Size = new Size(211, 46);
        btnPagos.Text = "Pagos";
        btnPagos.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnPagos.ForeColor = Color.FromArgb(20, 43, 78);
        btnPagos.BackColor = Color.White;
        btnPagos.IconChar = FontAwesome.Sharp.IconChar.CreditCard;
        btnPagos.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnPagos.IconColor = Color.FromArgb(103, 116, 137);
        btnPagos.IconSize = 22;
        btnPagos.FlatStyle = FlatStyle.Flat;
        btnPagos.FlatAppearance.BorderSize = 0;
        btnPagos.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnPagos.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnPagos.TextAlign = ContentAlignment.MiddleLeft;
        btnPagos.ImageAlign = ContentAlignment.MiddleLeft;
        btnPagos.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnPagos.Padding = new Padding(12, 0, 0, 0);
        btnPagos.Cursor = Cursors.Hand;
        btnPagos.UseVisualStyleBackColor = false;
        btnPagos.TabIndex = 5;
        btnPagos.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnReportes
        btnReportes.Name = "btnReportes";
        btnReportes.Location = new Point(12, 352);
        btnReportes.Size = new Size(211, 46);
        btnReportes.Text = "Reportes";
        btnReportes.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnReportes.ForeColor = Color.FromArgb(20, 43, 78);
        btnReportes.BackColor = Color.White;
        btnReportes.IconChar = FontAwesome.Sharp.IconChar.ChartColumn;
        btnReportes.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnReportes.IconColor = Color.FromArgb(103, 116, 137);
        btnReportes.IconSize = 22;
        btnReportes.FlatStyle = FlatStyle.Flat;
        btnReportes.FlatAppearance.BorderSize = 0;
        btnReportes.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnReportes.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnReportes.TextAlign = ContentAlignment.MiddleLeft;
        btnReportes.ImageAlign = ContentAlignment.MiddleLeft;
        btnReportes.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnReportes.Padding = new Padding(12, 0, 0, 0);
        btnReportes.Cursor = Cursors.Hand;
        btnReportes.UseVisualStyleBackColor = false;
        btnReportes.TabIndex = 6;
        btnReportes.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // lblAdministracion
        lblAdministracion.Name = "lblAdministracion";
        lblAdministracion.Location = new Point(24, 425);
        lblAdministracion.Size = new Size(190, 24);
        lblAdministracion.Text = "ADMINISTRACIÓN";
        lblAdministracion.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold, GraphicsUnit.Point);
        lblAdministracion.ForeColor = Color.FromArgb(103, 116, 137);
        lblAdministracion.BackColor = Color.Transparent;
        lblAdministracion.AutoEllipsis = true;
        // btnCatalogos
        btnCatalogos.Name = "btnCatalogos";
        btnCatalogos.Location = new Point(12, 459);
        btnCatalogos.Size = new Size(211, 46);
        btnCatalogos.Text = "Catálogos";
        btnCatalogos.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnCatalogos.ForeColor = Color.FromArgb(20, 43, 78);
        btnCatalogos.BackColor = Color.White;
        btnCatalogos.IconChar = FontAwesome.Sharp.IconChar.Tags;
        btnCatalogos.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnCatalogos.IconColor = Color.FromArgb(103, 116, 137);
        btnCatalogos.IconSize = 22;
        btnCatalogos.FlatStyle = FlatStyle.Flat;
        btnCatalogos.FlatAppearance.BorderSize = 0;
        btnCatalogos.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnCatalogos.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnCatalogos.TextAlign = ContentAlignment.MiddleLeft;
        btnCatalogos.ImageAlign = ContentAlignment.MiddleLeft;
        btnCatalogos.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnCatalogos.Padding = new Padding(12, 0, 0, 0);
        btnCatalogos.Cursor = Cursors.Hand;
        btnCatalogos.UseVisualStyleBackColor = false;
        btnCatalogos.TabIndex = 7;
        btnCatalogos.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // btnUsuarios
        btnUsuarios.Name = "btnUsuarios";
        btnUsuarios.Location = new Point(12, 509);
        btnUsuarios.Size = new Size(211, 46);
        btnUsuarios.Text = "Usuarios";
        btnUsuarios.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnUsuarios.ForeColor = Color.FromArgb(20, 43, 78);
        btnUsuarios.BackColor = Color.White;
        btnUsuarios.IconChar = FontAwesome.Sharp.IconChar.UserShield;
        btnUsuarios.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnUsuarios.IconColor = Color.FromArgb(103, 116, 137);
        btnUsuarios.IconSize = 22;
        btnUsuarios.FlatStyle = FlatStyle.Flat;
        btnUsuarios.FlatAppearance.BorderSize = 0;
        btnUsuarios.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnUsuarios.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnUsuarios.TextAlign = ContentAlignment.MiddleLeft;
        btnUsuarios.ImageAlign = ContentAlignment.MiddleLeft;
        btnUsuarios.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnUsuarios.Padding = new Padding(12, 0, 0, 0);
        btnUsuarios.Cursor = Cursors.Hand;
        btnUsuarios.UseVisualStyleBackColor = false;
        btnUsuarios.TabIndex = 8;
        btnUsuarios.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // lineaSesion
        lineaSesion.Name = "lineaSesion";
        lineaSesion.Location = new Point(0, 0);
        lineaSesion.Size = new Size(235, 1);
        lineaSesion.BackColor = Color.FromArgb(230, 234, 240);
        lineaSesion.Dock = DockStyle.Top;
        // iconUsuario
        iconUsuario.Name = "iconUsuario";
        iconUsuario.Location = new Point(16, 29);
        iconUsuario.Size = new Size(34, 34);
        iconUsuario.IconChar = FontAwesome.Sharp.IconChar.CircleUser;
        iconUsuario.IconFont = FontAwesome.Sharp.IconFont.Auto;
        iconUsuario.IconSize = 34;
        iconUsuario.IconColor = Color.FromArgb(20, 43, 78);
        iconUsuario.ForeColor = Color.FromArgb(20, 43, 78);
        iconUsuario.BackColor = Color.FromArgb(248, 250, 253);
        iconUsuario.TabStop = false;
        // lblUsuario
        lblUsuario.Name = "lblUsuario";
        lblUsuario.Location = new Point(60, 24);
        lblUsuario.Size = new Size(130, 23);
        lblUsuario.Text = "Usuario";
        lblUsuario.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        lblUsuario.ForeColor = Color.FromArgb(20, 43, 78);
        lblUsuario.BackColor = Color.Transparent;
        lblUsuario.AutoEllipsis = true;
        // lblRol
        lblRol.Name = "lblRol";
        lblRol.Location = new Point(60, 48);
        lblRol.Size = new Size(130, 20);
        lblRol.Text = "Administrador";
        lblRol.Font = new Font("Segoe UI", 8.5F, FontStyle.Regular, GraphicsUnit.Point);
        lblRol.ForeColor = Color.FromArgb(103, 116, 137);
        lblRol.BackColor = Color.Transparent;
        lblRol.AutoEllipsis = true;
        // btnCerrarSesion
        btnCerrarSesion.Name = "btnCerrarSesion";
        btnCerrarSesion.Location = new Point(195, 30);
        btnCerrarSesion.Size = new Size(30, 32);
        btnCerrarSesion.Text = "";
        btnCerrarSesion.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point);
        btnCerrarSesion.ForeColor = Color.FromArgb(20, 43, 78);
        btnCerrarSesion.BackColor = Color.FromArgb(248, 250, 253);
        btnCerrarSesion.IconChar = FontAwesome.Sharp.IconChar.ArrowRightFromBracket;
        btnCerrarSesion.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnCerrarSesion.IconColor = Color.FromArgb(103, 116, 137);
        btnCerrarSesion.IconSize = 20;
        btnCerrarSesion.FlatStyle = FlatStyle.Flat;
        btnCerrarSesion.FlatAppearance.BorderSize = 0;
        btnCerrarSesion.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnCerrarSesion.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnCerrarSesion.TextAlign = ContentAlignment.MiddleLeft;
        btnCerrarSesion.ImageAlign = ContentAlignment.MiddleLeft;
        btnCerrarSesion.TextImageRelation = TextImageRelation.ImageBeforeText;
        btnCerrarSesion.Padding = new Padding(0);
        btnCerrarSesion.Cursor = Cursors.Hand;
        btnCerrarSesion.UseVisualStyleBackColor = false;
        btnCerrarSesion.AccessibleName = "Cerrar sesión";
        btnCerrarSesion.TabIndex = 9;
        btnCerrarSesion.Click += btnCerrarSesion_Click;
        ayudaControles.SetToolTip(btnCerrarSesion, "Cerrar sesión");
        // tablaContenido
        tablaContenido.Name = "tablaContenido";
        tablaContenido.Location = new Point(0, 0);
        tablaContenido.Size = new Size(1068, 732);
        tablaContenido.Dock = DockStyle.Fill;
        tablaContenido.Margin = new Padding(0);
        tablaContenido.BackColor = Color.FromArgb(244, 246, 250);
        tablaContenido.ColumnCount = 1;
        tablaContenido.RowCount = 4;
        tablaContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        tablaContenido.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        tablaContenido.RowStyles.Add(new RowStyle(SizeType.Absolute, 112F));
        tablaContenido.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tablaContenido.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        // panelIntroduccion
        panelIntroduccion.Name = "panelIntroduccion";
        panelIntroduccion.Location = new Point(0, 0);
        panelIntroduccion.Size = new Size(1068, 58);
        panelIntroduccion.BackColor = Color.FromArgb(244, 246, 250);
        panelIntroduccion.Dock = DockStyle.Fill;
        panelIntroduccion.Margin = new Padding(0);
        // lblResumen
        lblResumen.Name = "lblResumen";
        lblResumen.Location = new Point(0, 0);
        lblResumen.Size = new Size(700, 44);
        lblResumen.Text = "Resumen del taller";
        lblResumen.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point);
        lblResumen.ForeColor = Color.FromArgb(20, 43, 78);
        lblResumen.BackColor = Color.Transparent;
        lblResumen.AutoEllipsis = true;
        // tarjetaResumen
        tarjetaResumen.Name = "tarjetaResumen";
        tarjetaResumen.Size = new Size(1068, 96);
        tarjetaResumen.Dock = DockStyle.Fill;
        tarjetaResumen.Margin = new Padding(0, 0, 0, 16);
        tarjetaResumen.Padding = new Padding(6);
        tarjetaResumen.BackColor = Color.White;
        // tablaIndicadores
        tablaIndicadores.Name = "tablaIndicadores";
        tablaIndicadores.Location = new Point(0, 0);
        tablaIndicadores.Size = new Size(1056, 84);
        tablaIndicadores.Dock = DockStyle.Fill;
        tablaIndicadores.Margin = new Padding(0);
        tablaIndicadores.BackColor = Color.White;
        tablaIndicadores.ColumnCount = 3;
        tablaIndicadores.RowCount = 1;
        tablaIndicadores.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        tablaIndicadores.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        tablaIndicadores.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33334F));
        tablaIndicadores.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        // tarjetaOrdenes
        tarjetaOrdenes.Name = "tarjetaOrdenes";
        tarjetaOrdenes.Location = new Point(0, 0);
        tarjetaOrdenes.Size = new Size(344, 84);
        tarjetaOrdenes.BackColor = Color.White;
        tarjetaOrdenes.Dock = DockStyle.Fill;
        tarjetaOrdenes.Margin = new Padding(0);
        // lblOrdenesTitulo
        lblOrdenesTitulo.Name = "lblOrdenesTitulo";
        lblOrdenesTitulo.Location = new Point(18, 10);
        lblOrdenesTitulo.Size = new Size(300, 23);
        lblOrdenesTitulo.Text = "Órdenes activas";
        lblOrdenesTitulo.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold, GraphicsUnit.Point);
        lblOrdenesTitulo.ForeColor = Color.FromArgb(103, 116, 137);
        lblOrdenesTitulo.BackColor = Color.Transparent;
        lblOrdenesTitulo.AutoEllipsis = true;
        lblOrdenesTitulo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // lblOrdenesValor
        lblOrdenesValor.Name = "lblOrdenesValor";
        lblOrdenesValor.Location = new Point(18, 34);
        lblOrdenesValor.Size = new Size(120, 42);
        lblOrdenesValor.Text = "—";
        lblOrdenesValor.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point);
        lblOrdenesValor.ForeColor = Color.FromArgb(20, 43, 78);
        lblOrdenesValor.BackColor = Color.Transparent;
        lblOrdenesValor.AutoEllipsis = true;
        // tarjetaReparacion
        tarjetaReparacion.Name = "tarjetaReparacion";
        tarjetaReparacion.Location = new Point(0, 0);
        tarjetaReparacion.Size = new Size(344, 84);
        tarjetaReparacion.BackColor = Color.White;
        tarjetaReparacion.Dock = DockStyle.Fill;
        tarjetaReparacion.Margin = new Padding(0);
        // lblReparacionTitulo
        lblReparacionTitulo.Name = "lblReparacionTitulo";
        lblReparacionTitulo.Location = new Point(18, 10);
        lblReparacionTitulo.Size = new Size(300, 23);
        lblReparacionTitulo.Text = "En reparación";
        lblReparacionTitulo.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold, GraphicsUnit.Point);
        lblReparacionTitulo.ForeColor = Color.FromArgb(103, 116, 137);
        lblReparacionTitulo.BackColor = Color.Transparent;
        lblReparacionTitulo.AutoEllipsis = true;
        lblReparacionTitulo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // lblReparacionValor
        lblReparacionValor.Name = "lblReparacionValor";
        lblReparacionValor.Location = new Point(18, 34);
        lblReparacionValor.Size = new Size(120, 42);
        lblReparacionValor.Text = "—";
        lblReparacionValor.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point);
        lblReparacionValor.ForeColor = Color.FromArgb(20, 43, 78);
        lblReparacionValor.BackColor = Color.Transparent;
        lblReparacionValor.AutoEllipsis = true;
        // tarjetaEntrega
        tarjetaEntrega.Name = "tarjetaEntrega";
        tarjetaEntrega.Location = new Point(0, 0);
        tarjetaEntrega.Size = new Size(344, 84);
        tarjetaEntrega.BackColor = Color.White;
        tarjetaEntrega.Dock = DockStyle.Fill;
        tarjetaEntrega.Margin = new Padding(0);
        // lblEntregaTitulo
        lblEntregaTitulo.Name = "lblEntregaTitulo";
        lblEntregaTitulo.Location = new Point(18, 10);
        lblEntregaTitulo.Size = new Size(300, 23);
        lblEntregaTitulo.Text = "Listas para entregar";
        lblEntregaTitulo.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold, GraphicsUnit.Point);
        lblEntregaTitulo.ForeColor = Color.FromArgb(103, 116, 137);
        lblEntregaTitulo.BackColor = Color.Transparent;
        lblEntregaTitulo.AutoEllipsis = true;
        lblEntregaTitulo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        // lblEntregaValor
        lblEntregaValor.Name = "lblEntregaValor";
        lblEntregaValor.Location = new Point(18, 34);
        lblEntregaValor.Size = new Size(120, 42);
        lblEntregaValor.Text = "—";
        lblEntregaValor.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point);
        lblEntregaValor.ForeColor = Color.FromArgb(20, 43, 78);
        lblEntregaValor.BackColor = Color.Transparent;
        lblEntregaValor.AutoEllipsis = true;
        // tarjetaOrdenesRecientes
        tarjetaOrdenesRecientes.Name = "tarjetaOrdenesRecientes";
        tarjetaOrdenesRecientes.Location = new Point(0, 0);
        tarjetaOrdenesRecientes.Size = new Size(740, 486);
        tarjetaOrdenesRecientes.BackColor = Color.White;
        tarjetaOrdenesRecientes.Dock = DockStyle.Fill;
        tarjetaOrdenesRecientes.Margin = new Padding(0);
        tarjetaOrdenesRecientes.Padding = new Padding(18);
        // tablaOrdenes
        tablaOrdenes.Name = "tablaOrdenes";
        tablaOrdenes.Location = new Point(0, 0);
        tablaOrdenes.Size = new Size(704, 450);
        tablaOrdenes.Dock = DockStyle.Fill;
        tablaOrdenes.Margin = new Padding(0);
        tablaOrdenes.BackColor = Color.White;
        tablaOrdenes.ColumnCount = 1;
        tablaOrdenes.RowCount = 3;
        tablaOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        tablaOrdenes.RowStyles.Add(new RowStyle(SizeType.Absolute, 50F));
        tablaOrdenes.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        tablaOrdenes.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        // panelTituloOrdenes
        panelTituloOrdenes.Name = "panelTituloOrdenes";
        panelTituloOrdenes.Location = new Point(0, 0);
        panelTituloOrdenes.Size = new Size(704, 50);
        panelTituloOrdenes.BackColor = Color.White;
        panelTituloOrdenes.Dock = DockStyle.Fill;
        panelTituloOrdenes.Margin = new Padding(0);
        // lblOrdenesRecientes
        lblOrdenesRecientes.Name = "lblOrdenesRecientes";
        lblOrdenesRecientes.Location = new Point(4, 1);
        lblOrdenesRecientes.Size = new Size(410, 30);
        lblOrdenesRecientes.Text = "Órdenes recientes";
        lblOrdenesRecientes.Font = new Font("Segoe UI Semibold", 13F, FontStyle.Bold, GraphicsUnit.Point);
        lblOrdenesRecientes.ForeColor = Color.FromArgb(20, 43, 78);
        lblOrdenesRecientes.BackColor = Color.Transparent;
        lblOrdenesRecientes.AutoEllipsis = true;
        // btnVerOrdenes
        btnVerOrdenes.Name = "btnVerOrdenes";
        btnVerOrdenes.Location = new Point(588, 5);
        btnVerOrdenes.Size = new Size(112, 34);
        btnVerOrdenes.Text = "Ver todas";
        btnVerOrdenes.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnVerOrdenes.ForeColor = Color.FromArgb(37, 99, 235);
        btnVerOrdenes.BackColor = Color.White;
        btnVerOrdenes.IconChar = FontAwesome.Sharp.IconChar.ArrowRight;
        btnVerOrdenes.IconFont = FontAwesome.Sharp.IconFont.Auto;
        btnVerOrdenes.IconColor = Color.FromArgb(37, 99, 235);
        btnVerOrdenes.IconSize = 14;
        btnVerOrdenes.FlatStyle = FlatStyle.Flat;
        btnVerOrdenes.FlatAppearance.BorderSize = 0;
        btnVerOrdenes.FlatAppearance.MouseOverBackColor = Color.FromArgb(240, 244, 250);
        btnVerOrdenes.FlatAppearance.MouseDownBackColor = Color.FromArgb(228, 236, 248);
        btnVerOrdenes.TextAlign = ContentAlignment.MiddleLeft;
        btnVerOrdenes.ImageAlign = ContentAlignment.MiddleLeft;
        btnVerOrdenes.TextImageRelation = TextImageRelation.TextBeforeImage;
        btnVerOrdenes.Padding = new Padding(5, 0, 0, 0);
        btnVerOrdenes.Cursor = Cursors.Hand;
        btnVerOrdenes.UseVisualStyleBackColor = false;
        btnVerOrdenes.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        // tablaEncabezadoOrdenes
        tablaEncabezadoOrdenes.Name = "tablaEncabezadoOrdenes";
        tablaEncabezadoOrdenes.Location = new Point(0, 0);
        tablaEncabezadoOrdenes.Size = new Size(704, 42);
        tablaEncabezadoOrdenes.Dock = DockStyle.Fill;
        tablaEncabezadoOrdenes.Margin = new Padding(0);
        tablaEncabezadoOrdenes.BackColor = Color.FromArgb(246, 248, 251);
        tablaEncabezadoOrdenes.ColumnCount = 4;
        tablaEncabezadoOrdenes.RowCount = 1;
        tablaEncabezadoOrdenes.Padding = new Padding(8, 0, 8, 0);
        tablaEncabezadoOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        tablaEncabezadoOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
        tablaEncabezadoOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 29F));
        tablaEncabezadoOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 23F));
        tablaEncabezadoOrdenes.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        // lblColumnaOrden
        lblColumnaOrden.Name = "lblColumnaOrden";
        lblColumnaOrden.Location = new Point(0, 0);
        lblColumnaOrden.Size = new Size(120, 42);
        lblColumnaOrden.Text = "Orden";
        lblColumnaOrden.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        lblColumnaOrden.ForeColor = Color.FromArgb(103, 116, 137);
        lblColumnaOrden.BackColor = Color.Transparent;
        lblColumnaOrden.AutoEllipsis = true;
        lblColumnaOrden.Dock = DockStyle.Fill;
        lblColumnaOrden.Margin = new Padding(8, 0, 0, 0);
        lblColumnaOrden.TextAlign = ContentAlignment.MiddleLeft;
        // lblColumnaCliente
        lblColumnaCliente.Name = "lblColumnaCliente";
        lblColumnaCliente.Location = new Point(0, 0);
        lblColumnaCliente.Size = new Size(120, 42);
        lblColumnaCliente.Text = "Cliente";
        lblColumnaCliente.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        lblColumnaCliente.ForeColor = Color.FromArgb(103, 116, 137);
        lblColumnaCliente.BackColor = Color.Transparent;
        lblColumnaCliente.AutoEllipsis = true;
        lblColumnaCliente.Dock = DockStyle.Fill;
        lblColumnaCliente.Margin = new Padding(8, 0, 0, 0);
        lblColumnaCliente.TextAlign = ContentAlignment.MiddleLeft;
        // lblColumnaEquipo
        lblColumnaEquipo.Name = "lblColumnaEquipo";
        lblColumnaEquipo.Location = new Point(0, 0);
        lblColumnaEquipo.Size = new Size(120, 42);
        lblColumnaEquipo.Text = "Equipo";
        lblColumnaEquipo.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        lblColumnaEquipo.ForeColor = Color.FromArgb(103, 116, 137);
        lblColumnaEquipo.BackColor = Color.Transparent;
        lblColumnaEquipo.AutoEllipsis = true;
        lblColumnaEquipo.Dock = DockStyle.Fill;
        lblColumnaEquipo.Margin = new Padding(8, 0, 0, 0);
        lblColumnaEquipo.TextAlign = ContentAlignment.MiddleLeft;
        // lblColumnaEstado
        lblColumnaEstado.Name = "lblColumnaEstado";
        lblColumnaEstado.Location = new Point(0, 0);
        lblColumnaEstado.Size = new Size(120, 42);
        lblColumnaEstado.Text = "Estado";
        lblColumnaEstado.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        lblColumnaEstado.ForeColor = Color.FromArgb(103, 116, 137);
        lblColumnaEstado.BackColor = Color.Transparent;
        lblColumnaEstado.AutoEllipsis = true;
        lblColumnaEstado.Dock = DockStyle.Fill;
        lblColumnaEstado.Margin = new Padding(8, 0, 0, 0);
        lblColumnaEstado.TextAlign = ContentAlignment.MiddleLeft;
        // tablaSinOrdenes
        tablaSinOrdenes.Name = "tablaSinOrdenes";
        tablaSinOrdenes.Location = new Point(0, 0);
        tablaSinOrdenes.Size = new Size(704, 340);
        tablaSinOrdenes.Dock = DockStyle.Fill;
        tablaSinOrdenes.Margin = new Padding(0);
        tablaSinOrdenes.BackColor = Color.White;
        tablaSinOrdenes.ColumnCount = 1;
        tablaSinOrdenes.RowCount = 3;
        tablaSinOrdenes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        tablaSinOrdenes.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        tablaSinOrdenes.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        tablaSinOrdenes.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        // lblSinOrdenes
        lblSinOrdenes.Name = "lblSinOrdenes";
        lblSinOrdenes.Location = new Point(0, 0);
        lblSinOrdenes.Size = new Size(680, 36);
        lblSinOrdenes.Text = "Sin órdenes para mostrar";
        lblSinOrdenes.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        lblSinOrdenes.ForeColor = Color.FromArgb(103, 116, 137);
        lblSinOrdenes.BackColor = Color.Transparent;
        lblSinOrdenes.AutoEllipsis = true;
        lblSinOrdenes.Dock = DockStyle.Fill;
        lblSinOrdenes.Margin = new Padding(12, 0, 12, 0);
        lblSinOrdenes.TextAlign = ContentAlignment.MiddleCenter;
        // lblPie
        lblPie.Name = "lblPie";
        lblPie.Location = new Point(0, 0);
        lblPie.Size = new Size(1068, 30);
        lblPie.Text = "AL DÍA  /  Gestión de reparaciones y mantenimiento";
        lblPie.Font = new Font("Segoe UI", 8F, FontStyle.Regular, GraphicsUnit.Point);
        lblPie.ForeColor = Color.FromArgb(103, 116, 137);
        lblPie.BackColor = Color.Transparent;
        lblPie.AutoEllipsis = true;
        lblPie.Dock = DockStyle.Fill;
        lblPie.Margin = new Padding(0);
        lblPie.TextAlign = ContentAlignment.BottomLeft;
        Controls.Add(panelAreaTrabajo);
        panelAreaTrabajo.Controls.Add(panelCuerpo);
        panelAreaTrabajo.Controls.Add(panelCabecera);
        panelCabecera.Controls.Add(lblTitulo);
        panelCabecera.Controls.Add(lblSeccion);
        panelCabecera.Controls.Add(iconCabecera);
        panelCabecera.Controls.Add(lblCabeceraDetalle);
        panelCabecera.Controls.Add(lineaCabecera);
        Controls.Add(panelLateral);
        panelLateral.Controls.Add(panelMenu);
        panelLateral.Controls.Add(panelMarca);
        panelLateral.Controls.Add(panelSesion);
        panelLateral.Controls.Add(lineaLateral);
        panelMarca.Controls.Add(fondoMarca);
        fondoMarca.Controls.Add(iconMarca);
        panelMarca.Controls.Add(lblMarca);
        panelMarca.Controls.Add(lblMarcaDetalle);
        panelMarca.Controls.Add(lineaMarca);
        panelMenu.Controls.Add(lblMenuPrincipal);
        panelMenu.Controls.Add(btnInicio);
        panelMenu.Controls.Add(btnClientes);
        panelMenu.Controls.Add(btnEquipos);
        panelMenu.Controls.Add(btnOrdenes);
        panelMenu.Controls.Add(btnInventario);
        panelMenu.Controls.Add(btnPagos);
        panelMenu.Controls.Add(btnReportes);
        panelMenu.Controls.Add(lblAdministracion);
        panelMenu.Controls.Add(btnCatalogos);
        panelMenu.Controls.Add(btnUsuarios);
        panelSesion.Controls.Add(lineaSesion);
        panelSesion.Controls.Add(iconUsuario);
        panelSesion.Controls.Add(lblUsuario);
        panelSesion.Controls.Add(lblRol);
        panelSesion.Controls.Add(btnCerrarSesion);
        panelCuerpo.Controls.Add(tablaContenido);
        tablaContenido.Controls.Add(panelIntroduccion, 0, 0);
        panelIntroduccion.Controls.Add(lblResumen);
        tablaContenido.Controls.Add(tarjetaResumen, 0, 1);
        tarjetaResumen.Controls.Add(tablaIndicadores);
        tablaContenido.Controls.Add(tarjetaOrdenesRecientes, 0, 2);
        tablaIndicadores.Controls.Add(tarjetaOrdenes, 0, 0);
        tarjetaOrdenes.Controls.Add(lblOrdenesTitulo);
        tarjetaOrdenes.Controls.Add(lblOrdenesValor);
        tablaIndicadores.Controls.Add(tarjetaReparacion, 1, 0);
        tarjetaReparacion.Controls.Add(lblReparacionTitulo);
        tarjetaReparacion.Controls.Add(lblReparacionValor);
        tablaIndicadores.Controls.Add(tarjetaEntrega, 2, 0);
        tarjetaEntrega.Controls.Add(lblEntregaTitulo);
        tarjetaEntrega.Controls.Add(lblEntregaValor);
        tarjetaOrdenesRecientes.Controls.Add(tablaOrdenes);
        tablaOrdenes.Controls.Add(panelTituloOrdenes, 0, 0);
        panelTituloOrdenes.Controls.Add(lblOrdenesRecientes);
        panelTituloOrdenes.Controls.Add(btnVerOrdenes);
        tablaOrdenes.Controls.Add(tablaEncabezadoOrdenes, 0, 1);
        tablaEncabezadoOrdenes.Controls.Add(lblColumnaOrden, 0, 0);
        tablaEncabezadoOrdenes.Controls.Add(lblColumnaCliente, 1, 0);
        tablaEncabezadoOrdenes.Controls.Add(lblColumnaEquipo, 2, 0);
        tablaEncabezadoOrdenes.Controls.Add(lblColumnaEstado, 3, 0);
        tablaOrdenes.Controls.Add(tablaSinOrdenes, 0, 2);
        tablaSinOrdenes.Controls.Add(lblSinOrdenes, 0, 1);
        tablaContenido.Controls.Add(lblPie, 0, 3);
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(244, 246, 250);
        ClientSize = new Size(1360, 850);
        Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        MinimumSize = new Size(1200, 820);
        Name = "FrmDashsbor";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Al Día · Gestión del taller";
        WindowState = FormWindowState.Maximized;
        tablaSinOrdenes.ResumeLayout(false);
        tablaEncabezadoOrdenes.ResumeLayout(false);
        panelTituloOrdenes.ResumeLayout(false);
        tablaOrdenes.ResumeLayout(false);
        tarjetaOrdenesRecientes.ResumeLayout(false);
        tarjetaEntrega.ResumeLayout(false);
        tarjetaReparacion.ResumeLayout(false);
        tarjetaOrdenes.ResumeLayout(false);
        tablaIndicadores.ResumeLayout(false);
        tarjetaResumen.ResumeLayout(false);
        panelIntroduccion.ResumeLayout(false);
        tablaContenido.ResumeLayout(false);
        lineaSesion.ResumeLayout(false);
        lineaMarca.ResumeLayout(false);
        fondoMarca.ResumeLayout(false);
        lineaLateral.ResumeLayout(false);
        panelSesion.ResumeLayout(false);
        panelMarca.ResumeLayout(false);
        panelMenu.ResumeLayout(false);
        panelLateral.ResumeLayout(false);
        lineaCabecera.ResumeLayout(false);
        panelCabecera.ResumeLayout(false);
        panelCuerpo.ResumeLayout(false);
        panelAreaTrabajo.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)iconCabecera).EndInit();
        ((System.ComponentModel.ISupportInitialize)iconMarca).EndInit();
        ((System.ComponentModel.ISupportInitialize)iconUsuario).EndInit();
        ResumeLayout(false);
    }

    #endregion

    private ToolTip ayudaControles;

    private Panel panelAreaTrabajo;
    private Panel panelCuerpo;
    private Panel panelCabecera;
    private Label lblTitulo;
    private Label lblSeccion;
    private FontAwesome.Sharp.IconPictureBox iconCabecera;
    private Label lblCabeceraDetalle;
    private Panel lineaCabecera;
    private Panel panelLateral;
    private Panel panelMenu;
    private Panel panelMarca;
    private Panel panelSesion;
    private Panel lineaLateral;
    private AlDia.UI.Controles.PanelTarjeta fondoMarca;
    private FontAwesome.Sharp.IconPictureBox iconMarca;
    private Label lblMarca;
    private Label lblMarcaDetalle;
    private Panel lineaMarca;
    private Label lblMenuPrincipal;
    private FontAwesome.Sharp.IconButton btnInicio;
    private FontAwesome.Sharp.IconButton btnClientes;
    private FontAwesome.Sharp.IconButton btnEquipos;
    private FontAwesome.Sharp.IconButton btnOrdenes;
    private FontAwesome.Sharp.IconButton btnInventario;
    private FontAwesome.Sharp.IconButton btnPagos;
    private FontAwesome.Sharp.IconButton btnReportes;
    private Label lblAdministracion;
    private FontAwesome.Sharp.IconButton btnCatalogos;
    private FontAwesome.Sharp.IconButton btnUsuarios;
    private Panel lineaSesion;
    private FontAwesome.Sharp.IconPictureBox iconUsuario;
    private Label lblUsuario;
    private Label lblRol;
    private FontAwesome.Sharp.IconButton btnCerrarSesion;
    private TableLayoutPanel tablaContenido;
    private Panel panelIntroduccion;
    private Label lblResumen;
    private AlDia.UI.Controles.PanelTarjeta tarjetaResumen;
    private TableLayoutPanel tablaIndicadores;
    private Panel tarjetaOrdenes;
    private Label lblOrdenesTitulo;
    private Label lblOrdenesValor;
    private Panel tarjetaReparacion;
    private Label lblReparacionTitulo;
    private Label lblReparacionValor;
    private Panel tarjetaEntrega;
    private Label lblEntregaTitulo;
    private Label lblEntregaValor;
    private AlDia.UI.Controles.PanelTarjeta tarjetaOrdenesRecientes;
    private TableLayoutPanel tablaOrdenes;
    private Panel panelTituloOrdenes;
    private Label lblOrdenesRecientes;
    private FontAwesome.Sharp.IconButton btnVerOrdenes;
    private TableLayoutPanel tablaEncabezadoOrdenes;
    private Label lblColumnaOrden;
    private Label lblColumnaCliente;
    private Label lblColumnaEquipo;
    private Label lblColumnaEstado;
    private TableLayoutPanel tablaSinOrdenes;
    private Label lblSinOrdenes;
    private Label lblPie;
}
